Faster Matchifile Parsing and Checks.
CPJKU/partitura pull request #307
Opened 2023-08-10 16:16 UTC by manoskary

This PR presents a solution for faster checking of empty and duplicate lines in matchfiles using numpy arrays and numpy vectorization.

- Addresses #306

2023-08-29 09:47 UTC, huispaty submitted a review, later dismissed
The approach you've presented is efficient but could be simplified. If you're open to it, I would suggest considering the alternative one-liner I proposed earlier.

2023-08-29 09:47 UTC, huispaty commented on partitura/io/importmatch.py
This changed version parses match files in the same amount of time as the version without any duplicate line checks (approx. 27 secs for the match file posted in the corresponding [issue](https://github.com/CPJKU/partitura/issues/306)). However, it adds quite a few additional lines and seemingly overcomplicates things... What about this alternative one-liner solution (also speeds up computation by a bit (~ 2 secs):

```
    with open(filename) as f:
        raw_lines = f.read().splitlines()

    version = get_version(raw_lines[0])

    from_matchline_methods = FROM_MATCHLINE_METHODSV1
    if version < Version(1, 0, 0):
        from_matchline_methods = FROM_MATCHLINE_METHODSV0

    raw_lines = list(set(raw_lines))
    parsed_lines = [
        parse_matchline(line, from_matchline_methods, version) for line in raw_lines
    ]
    
    parsed_lines = [pl for pl in parsed_lines if pl is not None]

    mf = MatchFile(lines=parsed_lines)
```

2023-08-29 11:13 UTC, manoskary commented on partitura/io/importmatch.py
There are two issues your originally proposed code that I want to avoid with my addition:
1. Consecutive loops in pure python are slow (normally numpy functions should work faster maybe we can put several pieces to the test)
2. There are no warnings or indications about what is being discarded. The original version of the code (the slow one) had explicit warnings about repeated lines.

2023-08-29 12:30 UTC, huispaty commented on partitura/io/importmatch.py
1. The two loops were part of the script previously (before the duplicate lines warning was introduced) but can be summarised into one easily.
2. I agree about the warnings part - though this is now reduced to merely indicating how many lines were dropped (instead of reporting which ones, as was done previously).

2023-08-29 13:06 UTC, manoskary commented on partitura/io/importmatch.py
[Here](https://stackoverflow.com/questions/46839277/series-unique-vs-list-of-set-performance) is a source comparing the `unique` with `list(set())`. Indeed for strings the overhead is not too much.

2023-09-20 12:20 UTC, neosatrapahereje requested changes

2023-09-20 12:24 UTC, manoskary commented on partitura/io/importmatch.py
> +    _, idx = np.unique(np_lines, return_index=True)
I think the lines are strings and therefore in numpy format they are read as python objects, therefore there would be easy sorting. Or maybe, I am missing something...

2023-09-20 12:24 UTC, manoskary commented on partitura/io/importmatch.py
> +    if len_raw_lines != len_after_empty_lines:
Ok then, I will remove the warnings.

2023-09-20 12:55 UTC, neosatrapahereje requested changes

2023-09-20 13:37 UTC, neosatrapahereje approved these changes

2023-09-20 13:44 UTC, merged