PR for Release 1.4.1
CPJKU/partitura pull request #335
Opened 2023-10-24 15:53 UTC by fosfrancesco

## Bug Fixes
- remove unnecessary escape character for correct parsing of sharp accidentals in nakamura match files.
- don't consider the propriety `doc_order` for sorting notes in the `matchfile_from_alignment` function if it is not present. This propriety is only present in parts from musicxml scores and previously resulted in an exception for other score formats. This solves https://github.com/CPJKU/partitura/issues/326
- during matchfile parsing, voice info is now parsed as follows: If there is no voice info, all notes get assigned voice number 1. If there is only voice info for the solo voice, the non-solo voiced notes get voice 2. If multiple notes have different voices, but not every note has a voice annotated, those with voice annotation get the annotated voice number and those without voice annotation get assigned the max voice+1 voice number. Previously all notes were assigned to voice 1 if there were any None voiced note
- during matchfile parsing, all note classes are now matched correctly. Previously classes `MatchSnoteTrailingScore` and `MatchSnoteNoPlayedNote` were always marked as `MatchSnoteDeletion`  and `MatchHammerBounceNote`, `MatchTrailingPlayedNote`, `MatchTrillNote` always ended up as `MatchInsertionNote`. This solves https://github.com/CPJKU/partitura/issues/286
- during matchfile parsing, lines which can't be parsed are removed. Before they ended up as `None` in the output.

2023-10-24 17:05 UTC, manoskary requested changes
This PR addresses the latest minor release. I have some minor recommendations and comments left for correction.

2023-10-24 17:05 UTC, manoskary commented on partitura/io/matchfile_base.py
> +            raise MatchError("")
Same here.

2023-10-25 06:01 UTC, sildater commented on partitura/io/importmatch.py
> +        elif any(a.startswith("v") for a in note.ScoreAttributesList):
yes that would also make sense. what about reviewing whether the code works instead of blocking a PR with implementation style requests?

2023-10-25 06:06 UTC, sildater commented on partitura/io/matchfile_base.py
> +            raise MatchError("")
Please check what the MatchError is used for.

2023-10-25 06:08 UTC, sildater commented on partitura/io/matchfile_base.py
> +            raise MatchError("")
Added a string to make it the same across all uses.

2023-10-25 06:08 UTC, sildater commented on partitura/io/importmatch.py
> -
done.

2023-10-25 06:08 UTC, sildater commented on partitura/io/importmatch.py
> +    parsed_lines = [line for line in parsed_lines_raw if line is not None]
Added a test. Refactored to vectorized style.

2023-10-25 08:48 UTC, huispaty commented on partitura/io/importmatch.py
> +    n_voices = set([n.voice for n in part.notes])
`n_voices` is a set because np.unique throws a TypeError if there are no voice annotations for some or all notes, causing `None` type voices.

2023-10-25 09:31 UTC, huispaty approved these changes

2023-10-25 10:41 UTC, manoskary approved these changes
This PR includes minor fixes. Everything looks good.

2023-10-25 12:27 UTC, merged