Add a parameter to ignore invisible objects when parsing MusicXML files
CPJKU/partitura pull request #401
Opened 2024-11-26 16:26 UTC by leleogere

As explained in #395, it can sometimes be useful to parse a score only with information available to a human, i.e. visible information. MusicXML allow some elements to be invisible with the attribute `print-object` that can be set to `"yes"` or `"no"`.

This PR simply add a new parameter `ignore_invisible_objects` to the function `load_musicxml`, defaulting to `False` for old behavior. When set to `True`, the loop over all elements in a measure will first check if the element has an attribute `print-object` set to `"no"`, and if so, continue to the next loop without adding the object to the score (for `note` objects, I had to update the position with the duration anyway to avoid errors with backups when notes were not added to the part, I don't know if this can cause issues downstream?).

2024-12-05 15:44 UTC, CarlosCancino-Chacon commented
Hey @leleogere, thanks for the contribution! It would be great if you could add a test case for this feature (for example in`partitura/tests/test_xml.py`).

2024-12-10 08:27 UTC, leleogere commented
I'll do that this week!

2024-12-13 16:54 UTC, leleogere commented
Added some tests!

2024-12-31 10:04 UTC, manoskary requested changes
This PR covers the support of invisible objects when parsing MusicXML. 
The implementation is great, but also raises some preference questions as well:
- Should notes be allowed to be invisible?
- Should invisible mean skip parsing or should it be a `TimedObject` attribute that forces it to not be returned when `part.iter_all` is called and relevant functions?

As per this review, all questions are high-level and do not necessarily need to be addressed or correct the provided implementation but rather open a discussion.

2025-01-15 10:37 UTC, leleogere commented on partitura/io/importmusicxml.py
> +        # Will probably not skip everything, but works at least for notes and rests
The most frequent case I've seen invisible notes is to simulate trills/mordents/tremolos for MIDI export (this is not needed in MuseScore as it automatically render those notes, but some other software may not? Or some people might want to end the trill in a custom way?). When parsing this kind of score, I would like to only have access to visible note (eventually with trill/mordent/tremolo information), but not to notes that have been added here for the sole purpose of MIDI export.

A lot of scores in ASAP have such invisible notes, for example in measures 21 and 23 of [Chopin/Sonata_2/2nd_no_repeat/xml_score.musicxml](https://github.com/CPJKU/asap-dataset/blob/main/Chopin/Sonata_2/2nd_no_repeat/xml_score.musicxml).

2025-01-15 10:57 UTC, manoskary commented on partitura/io/importmusicxml.py
> +        # Will probably not skip everything, but works at least for notes and rests
Thank you, I hadn't thought of such an application. This would then definitely be a great addition to partitura.
Thanks again for all your work. I will resolve this review comment once the PR is ready for merge.

2025-01-15 11:08 UTC, leleogere commented on tests/test_xml.py
Are you sure about the loop? As I'm testing for the presence/absence of specific elements in the score, it does not make a lot of sense to run the same test for all eventual future scores to test, does it?

I'll adapt the test to avoid the diff!

2025-01-20 16:03 UTC, leleogere commented on tests/test_xml.py
I changed the test to avoid the string diff, let me know if that's better. I'm still not sure about the loop, what do you think about it?

2025-01-20 20:18 UTC, manoskary commented on tests/test_xml.py
No I guess the loop is ok, you don't have to change it.

2025-01-20 20:20 UTC, manoskary approved these changes
Great addition for parsing or skipping invisible objects in musicxml. Cases for invisible notes can be spelled out trills and others. This PR includes tests too.

2025-01-21 14:58 UTC, merged